language: python

python:
  - 2.7

sudo: required

services:
  - docker

env:
  global:
    - REPO=driesschulten/aws-php-circleci
    - secure: OSxGEHsFYXofWoK6t6gd0IdWPDvcIZ6v1FWfOpw2wjqV4fPsyltrOvihkvwwXqCYP9Q/BiuXAX6ET1ADaQFjIVxL/GOBcPNzp1FAfx1Vh35hkkuA/44sR9LETA2k/dHYOIjO9wnQZVXOZICPdW7sQfnCZb+GDr6sGMJ+OKP3S49SAEuegkfWvL3+/QykzaIHUP2Lnmvg0E4XezMYAyIWJi8W0NUIiApcgO/eTcYyWiBc4GKT5gZyM0avFK2f4+bUbEZvAh7XGrV8vZkaJcquNSYGHwYqnwOkiYe55bHqeOBM74sMF3KIZXjPNynNf+OyXB+BdUaTjx/w+KFVx1pXYERz8qjLtyNLrUVTm+qdBKy6N6skliHwD9Yp90K+df2DzgKy6wan+3xphDpMGaVUHqvJcKiakw5CrJqYNPDlXg8dIcdXU2iVXfrOOInf+BoDK3nTPgUawRYJGobOPryo2NkOeuR2GXJHbz0F1wpAASuBxHw3vK51VBWaX0LxKmC8HLqezhKgIk+co8cUPmgSJeNaiPZkgwZhwnPjvDXWE88ujQvxjnExgBFZqvBy8lrC7v+seAe3VHi+07veeAZE3aFjVy6C8aPtXiDxltVq+4s9ivnok+FCCrTTZehu1vCyILFWe8DnZpsu6XP6R82EOgAPPn+OJYbHCrnr9Ew0wm0=
    - secure: rj8YrOxxOMWBiNhhrn2ZgkDXo3WWlRCJjva+az6Wx+hCBvO4+I/eQ2n6Iwi9Kc6vM96GGt3jiRpfFkYr4Wxad2NphDRic75sUs0L4nym/aBDU7Fq6vV7ebwxTX244ZOQyqR7pLrqwJFkjkIKf4rLxks5/yPChU/4HA/h1cPlI2TC83ynAkaSgDXlyB1WAJdjNmJC6AGoygR3gKmIMHAGsywXDDo0Z8NjnTedXmqP6W/+vp4rETgrbdpAQ6ScLObHQJWjU3mlCyNT0ZtUzKgoxD2iA4b4UUPgYqYP39/oQZF70WhyzPUIWIogpDqjgNXQ1qXaVSF8X/LkfPUGhHFco8emaCe0hjVS58KFRekjhBB/oF5TaURoREBcUkRIrP0odpdYRPbFkUUZQEoiR5hqtKFXrHLDJn/ns1tlE2d/+yrADI79q0GmjrIN4/FzJFMdPh78uPgxzRiTkzqAy7xoaWRxM7X+thwjhHhPgmp9UIWeMXw9sFqqUu8y+eOHyc4TJxWjhIoMaBOn6G+I9Bu0OSMeP22ILnh8xjK+LZEd4fWspC8hIO+owO0ymDuPTEVn/6wN11pINudpRXBzLYWaSkgnSfmSxxA0qOtyL02n/+1EmWn0aaIeJf1J5JkVX3BKV5z4yDrSWvO307K8vIM6GiEAGsm4rHA+PwzIBAAoJi4=

install:
  - docker build -t $REPO .

script: echo 'no tests!'

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag $REPO $REPO:latest
  - if [[ $TRAVIS_TAG ]]; then docker tag $REPO $REPO:$TRAVIS_TAG; fi
  - docker push $REPO
